# verbose: true
instrumentation:
  root: ./packages
  excludes:
    - "**/jspm_packages/**"
    - "**/node_modules/**"
    - "**/reports/**"
    - "**/dist/**"
    - "**/lib/**"
reporting:
  reports:
    - json
